### ISSUE TITLE
Python environment

### ISSUE THREAD

**Issue by QienJane** [lbinmeng/bci_adv_defense#1]
Dear Sir/Madam,

I recently read your article published in the journal Future Generation Computer Systems. I am very interested in your research on the application of adversarial attacks in the field of brain-computer interfaces, especially the innovative aspects of your work.

I downloaded the source code you provided and tried to run it, but I encountered some difficulties as I could not find information about the required Python environment and package versions.

Could you please advise me on which version of Python and which packages I need to successfully run these codes? Any guidance or help you can provide on this issue would be greatly appreciated.

Thank you very much for your support and assistance on this matter. I look forward to hearing from you soon.

Best regards,

**Comment by lbinmeng** [comment]
Sorry to take so long to reply to you. Thank you very much for your interest in our work. We uploaded the environment file, hoping it can help you!

**Comment by QienJane** [comment]
诶，这个bci_adv_defense项目的code页没有提到所需要的环境哇，下面是code页的截图：
![image](https://user-images.githubusercontent.com/84821239/229061814-81d3a70c-4f7e-498d-b8b1-1c7d996e63bc.png)

**Comment by lbinmeng** [comment]
> 诶，这个bci_adv_defense项目的code页没有提到所需要的环境哇，下面是code页的截图：
> ![image](https://user-images.githubusercontent.com/84821239/229061814-81d3a70c-4f7e-498d-b8b1-1c7d996e63bc.png)

environment.yml就是，使用conda clone就可以配置了

**Comment by QienJane** [comment]
好滴，超级感谢您！！

**Comment by QienJane** [comment]
孟璐斌博士，
&nbsp; &nbsp; &nbsp; 您好！很抱歉以这种方式再次打扰到您！我按照您的指示下载了下四分类的数据：里面包括A01T.mat、A01E.mat，...，A09T.mat、A09E.mat等数据文件。


&nbsp; &nbsp; &nbsp; 但是在pycharm中（左图）运行您的代码的时候，发现读取到的A01T.mat、A01E.mat...这些数据里还有“s”、“etyp”、“epos”这些键值对。
然而直接从您论文中给出的BNCI网址里下载的A01T.mat、A01E.mat，...，A09T.mat、A09E.mat这个数据集中的原始数据格式是不包括“s”、“etyp”、“epos”这些变量的（右图），所以冒昧问下您从BNCI网址中下载过原始数据后是不是又进行了一系列预处理呢？因为原始数据中的数据集中没有您的Python代码里写的这些“s”、“etyp”、“epos”这些键值对。


&nbsp; &nbsp; &nbsp; 实在是由于我学术浅薄，复现不出您的预处理过程！
&nbsp; &nbsp; &nbsp; 如果您进行过预处理的话，冒昧问下可以发一下预处理部分的.py文件给我嘛？这将对我有很大的帮助，万分感谢您！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lbinmeng/bci_adv_defense"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月31日(星期五) 下午4:05
***@***.***&gt;;
抄送:&nbsp;"广州大学 詹倩倩 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [lbinmeng/bci_adv_defense] Python environment (Issue #1)





  
诶，这个bci_adv_defense项目的code页没有提到所需要的环境哇，下面是code页的截图：
 
  
environment.yml就是，使用conda clone就可以配置了
